### ISSUE TITLE
Next steps after installing to integrate with GNOME settings?

### ISSUE THREAD

**Issue by RaghavRao** [uunicorn/open-fprintd#1]
Hi, I have 06cb:009a, I got it paired and enrolled, built and installed the fork of libfprint2 and open-fprintd.

How do I use my enrolled fingerprint (or help develop) to use my fingerprint for sudo access?

**Comment by uunicorn** [comment]
Hi @RaghavRao , I don't think `libfprint2` currently has a support for this device. You can try following instructions from [this comment](https://github.com/uunicorn/python-validity/issues/3#issuecomment-655770194) and then steps 4-7 from [this comment](https://github.com/uunicorn/python-validity/issues/3#issuecomment-655477344).

**Comment by RaghavRao** [comment]
Thank you!
I am currently on fedora, so I think I'll need to build from source.
Where can I grab fprintd-clients from?

**Comment by uunicorn** [comment]
Here's my fork: https://gitlab.freedesktop.org/uunicorn/fprintd/-/tree/master .
It is almost identical to the upstream, except building the `fprintd` daemon is option (to avoid additional buildeps). 
Look inside the `debian/` to see the packaging rules specific for `fprintd-clients`. You may not need to build if from sources - just install fprintd and remove bits which are not included in `fprintd-clients` .

**Comment by RaghavRao** [comment]
Hi!

I'm running into a couple Dbus permission issues on open-fprintd (I copy
pasted the instructions from the comment before the ppa was made, including
the DBus conf)

```

sudo python /usr/local/lib/open-fprintd/open-fprintd
Traceback (most recent call last):
  File "/usr/local/lib/open-fprintd/open-fprintd", line 23, in <module>
    bus_name = dbus.service.BusName('net.reactivated.Fprint',
dbus.SystemBus())
  File "/usr/lib64/python3.8/site-packages/dbus/service.py", line 133, in
__new__
    retval = bus.request_name(name, name_flags)
  File "/usr/lib64/python3.8/site-packages/dbus/bus.py", line 303, in
request_name
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib64/python3.8/site-packages/dbus/connection.py", line 652,
in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied:
Request to own name refused by policy

```

Any ideas?

Thanks

**Comment by uunicorn** [comment]
It looks like you are missing this file https://github.com/uunicorn/open-fprintd/blob/master/dbus_service/net.reactivated.Fprint.conf in the right place. 
I think `setup.py` it should have copied it for you if you ran something like
```
./setup.py install --force --prefix=/usr --root=/
```

But I'm new to python packaging.

**Comment by RaghavRao** [comment]
No worries!

I ran that, and I have it installed in
/usr/share/dbus-1/system.d/net.reactivated.Fprint.conf

Contents:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-BUS Bus Configuration
1.0//EN"
                            "
http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>
    <policy user="root">
        <allow send_destination="io.github.uunicorn.Fprint"/>
        <allow send_interface="io.github.uunicorn.Fprint"/>
        <allow own="net.reactivated.Fprint"/>
    </policy>

    <policy context="default">
        <allow send_destination="net.reactivated.Fprint"/>
        <allow send_interface="net.reactivated.Fprint"/>
    </policy>
</busconfig>

Same error though...

**Comment by uunicorn** [comment]
Odd. Perhaps `dbus` has failed to parse this .conf file. Can you check the logs?

**Comment by RaghavRao** [comment]
Sure! Where are they located? Is it just dmesg? Or

**Comment by uunicorn** [comment]
Try `journalctl -u dbus.service`

**Comment by RaghavRao** [comment]
A reboot fixed it, that was really strange. 
fprintd-enroll and verify works now!
